parts:
  #Should Slot Manager be enabled?(Reserved Slots, Joinmessage and -sound)
  slotmanager: true 

#Slot Manager Configuration
slotmanager:
  reserved:
    #How many slots should be reserved? (-1 equals all without the allowplayers limitation)
    count: -1
    #Should we allow normal players to join reserved slots?
    allowplayers: true
  join:
    #Template for customized Joinmessage and -sound:
    #Username:
    #  message: TextToDisplay
    #  sound: UrlToSound
    #When filled it looks along the lines of this:
    #Xaymar:
    #  message: 'This is a text.'
    #  sound: http://example.com/404.ogg
