author: Michael Dirks
database: true
description: "Provides an all-in-one approach for server hosters. Easy setup and management!"
main: me.michaeldirks.plugins.nullessentials.NullEssentials
name: NullEssentials
startup: postworld
depend: [Spout]
url: http://levelnull.de/
version: '0.3'
permissions:
  ne.slotmanager.reserved:
    default: op
    description: Allows the user to use reserved slots and kick users using reserved slots.
  ne.slotmanager.sound:
    default: op
    description: Allows the user to play a Joinsound after joining.
  ne.slotmanager.message:
    default: op
    description: Allows the user to replace the default join notification with a custom Joinmessage.
commands:
  ne:
    description: Control Null Essentials through Commands
    usage: /<command> <args>
    alias: []