parts:
  slotmanager: true
  playerlist: true
slotmanager:
  reserved:
    count: -1
    allowplayers: true
  extra:
    #template:
    #  join: Join
    #  leave: Leave
    #  sound: http://example.org/wav.wav